default: styles/night.scss
more-stars-night: styles/night-stars.scss
ocean: styles/ocean.scss
ocean-blur: styles/ocean-blur.scss
vapor: styles/vapor.scss
mastodon-dark: styles/application.scss
mastodon-light: styles/mastodon-light.scss
contrast: styles/contrast.scss
fairy-floss: styles/fairy-floss.scss
win95: styles/win95.scss
